### ISSUE TITLE
[Question] Cauldron Support

### ISSUE THREAD

**Issue by micmou** [addstar/Prism-Bukkit#10]
Does build 14 on your jenkins support Cauldron builds specifically cauldron 1403 found here
https://prok.pw/git/Prototik/KCauldron

**Comment by addstar** [comment]
I have never used Cauldron so I can't say if it works. I can only suggest you try it out.
Sorry, but I can't help you with this one.

**Comment by micmou** [comment]
Actually it does appear to work as intended even pulling correct data for mod items :D and works well with the webui

**Comment by addstar** [comment]
That's great to know! :grinning: 
Best of luck with everything.
