### ISSUE TITLE
1.8.3 NullPointer Spam

### ISSUE THREAD

**Issue by recon88** [addstar/Prism-Bukkit#8]
Getting a lot of NPEs after updating to 1.8.3

http://pastebin.com/unJLJjtX

**Comment by rumickon** [comment]
For @addstar.
I think, that is the solve of the problem: https://github.com/rumickon/Prism-Bukkit/commit/97b8fa4e331e222e511b41e38c83d28674afac2a

**Comment by addstar** [comment]
Great catch @rumickon! Thanks :grin: 

@recon88 it should be fixed in the latest build.
